Repository kakao-tech-campus-2nd-step3/Team3_BE, pull requests merged in 2024-10, with the labels that each got.

#32 [feature]: Payments CRUD 구현
  src/main/java/com/splanet/splanet/core/exception/ErrorCode.java
  src/main/java/com/splanet/splanet/payment/controller/PaymentController.java
  src/main/java/com/splanet/splanet/payment/dto/PaymentRequest.java
  src/main/java/com/splanet/splanet/payment/dto/PaymentResponse.java
  src/main/java/com/splanet/splanet/payment/entity/Payment.java
  src/main/java/com/splanet/splanet/payment/service/PaymentService.java
  src/test/java/com/splanet/splanet/payment/service/PaymentServiceTest.java
Labels: ✨feature

#34 [feature]: Plan API 구현
  build.gradle
  src/main/java/com/splanet/splanet/core/exception/ErrorCode.java
  src/main/java/com/splanet/splanet/core/exception/GlobalExceptionHandler.java
  src/main/java/com/splanet/splanet/plan/controller/PlanController.java
  src/main/java/com/splanet/splanet/plan/dto/PlanRequestDto.java
  src/main/java/com/splanet/splanet/plan/dto/PlanResponseDto.java
  src/main/java/com/splanet/splanet/plan/entity/Plan.java
  src/main/java/com/splanet/splanet/plan/mapper/PlanMapper.java
  src/main/java/com/splanet/splanet/plan/repository/PlanRepository.java
  src/main/java/com/splanet/splanet/plan/service/PlanService.java
  src/test/java/com/splanet/splanet/plan/entity/PlanTest.java
  src/test/java/com/splanet/splanet/plan/service/PlanServiceTest.java
  src/test/java/com/splanet/splanet/user/service/UserServiceTest.java
Labels: ✨feature

#38 [feature]: Comments CRUD 구현
  src/main/java/com/splanet/splanet/comment/controller/CommentController.java
  src/main/java/com/splanet/splanet/comment/dto/CommentRequest.java
  src/main/java/com/splanet/splanet/comment/dto/CommentResponse.java
  src/main/java/com/splanet/splanet/comment/entity/Comment.java
  src/main/java/com/splanet/splanet/comment/repository/CommentRepository.java
  src/main/java/com/splanet/splanet/comment/service/CommentService.java
  src/main/java/com/splanet/splanet/core/exception/ErrorCode.java
  src/test/java/com/splanet/splanet/comment/entity/CommentTest.java
  src/test/java/com/splanet/splanet/comment/service/CommentServiceTest.java
Labels: ✨feature

#40 [refactor]: Subscription API 수정
  src/main/java/com/splanet/splanet/subscription/controller/SubscriptionController.java
  src/main/java/com/splanet/splanet/subscription/dao/SubscriptionDao.java
  src/main/java/com/splanet/splanet/subscription/dto/SubscriptionDto.java
  src/main/java/com/splanet/splanet/subscription/dto/SubscriptionRequest.java
  src/main/java/com/splanet/splanet/subscription/dto/SubscriptionResponse.java
  src/main/java/com/splanet/splanet/subscription/service/SubscriptionService.java
  src/test/java/com/splanet/splanet/subscription/service/SubscriptionServiceTest.java
Labels: ✨feature

#42 [feature]: Refresh Token 로직 구현
  build.gradle
  docker-compose.yml
  src/main/java/com/splanet/splanet/config/RedisConfig.java
  src/main/java/com/splanet/splanet/config/SecurityConfig.java
  src/main/java/com/splanet/splanet/jwt/JwtAuthenticationFilter.java
  src/main/java/com/splanet/splanet/jwt/JwtTokenProvider.java
  src/main/java/com/splanet/splanet/jwt/controller/TokenController.java
  src/main/java/com/splanet/splanet/jwt/entity/RefreshToken.java
  src/main/java/com/splanet/splanet/jwt/repository/RefreshTokenRepository.java
  src/main/java/com/splanet/splanet/jwt/service/TokenService.java
  src/main/java/com/splanet/splanet/oauth/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/splanet/splanet/oauth/TokenController.java
  src/main/resources/application.yml
Labels: ✨feature

#43 [refactor]: 구독, 결제, 댓글 엔티티 연관관계 설정
  src/main/java/com/splanet/splanet/subscription/entity/Subscription.java
  src/main/java/com/splanet/splanet/subscription/service/SubscriptionService.java
  src/main/java/com/splanet/splanet/user/entity/User.java
  src/test/java/com/splanet/splanet/subscription/service/SubscriptionServiceTest.java
Labels: ✨feature

#44 [merge]: 5주차 코드 develop 에 병합
  build.gradle
  docker-compose.yml
  src/main/java/com/splanet/splanet/comment/controller/CommentController.java
  src/main/java/com/splanet/splanet/comment/dto/CommentRequest.java
  src/main/java/com/splanet/splanet/comment/dto/CommentResponse.java
  src/main/java/com/splanet/splanet/comment/entity/Comment.java
  src/main/java/com/splanet/splanet/comment/repository/CommentRepository.java
  src/main/java/com/splanet/splanet/comment/service/CommentService.java
  src/main/java/com/splanet/splanet/config/RedisConfig.java
  src/main/java/com/splanet/splanet/config/SecurityConfig.java
  src/main/java/com/splanet/splanet/core/exception/ErrorCode.java
  src/main/java/com/splanet/splanet/core/exception/GlobalExceptionHandler.java
  src/main/java/com/splanet/splanet/jwt/JwtAuthenticationFilter.java
  src/main/java/com/splanet/splanet/jwt/JwtTokenProvider.java
  src/main/java/com/splanet/splanet/jwt/controller/TokenController.java
  src/main/java/com/splanet/splanet/jwt/entity/RefreshToken.java
  src/main/java/com/splanet/splanet/jwt/repository/RefreshTokenRepository.java
  src/main/java/com/splanet/splanet/jwt/service/TokenService.java
  src/main/java/com/splanet/splanet/oauth/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/splanet/splanet/payment/controller/PaymentController.java
  src/main/java/com/splanet/splanet/payment/dto/PaymentRequest.java
  src/main/java/com/splanet/splanet/payment/dto/PaymentResponse.java
  src/main/java/com/splanet/splanet/payment/entity/Payment.java
  src/main/java/com/splanet/splanet/payment/service/PaymentService.java
  src/main/java/com/splanet/splanet/plan/controller/PlanController.java
  src/main/java/com/splanet/splanet/plan/dto/PlanRequestDto.java
  src/main/java/com/splanet/splanet/plan/dto/PlanResponseDto.java
  src/main/java/com/splanet/splanet/plan/entity/Plan.java
  src/main/java/com/splanet/splanet/plan/mapper/PlanMapper.java
  src/main/java/com/splanet/splanet/plan/repository/PlanRepository.java
  src/main/java/com/splanet/splanet/plan/service/PlanService.java
  src/main/java/com/splanet/splanet/subscription/controller/SubscriptionController.java
  src/main/java/com/splanet/splanet/subscription/dao/SubscriptionDao.java
  src/main/java/com/splanet/splanet/subscription/dto/SubscriptionDto.java
  src/main/java/com/splanet/splanet/subscription/dto/SubscriptionRequest.java
  src/main/java/com/splanet/splanet/subscription/dto/SubscriptionResponse.java
  src/main/java/com/splanet/splanet/subscription/entity/Subscription.java
  src/main/java/com/splanet/splanet/subscription/service/SubscriptionService.java
  src/main/java/com/splanet/splanet/user/controller/UserController.java
  src/main/java/com/splanet/splanet/user/entity/User.java
  src/main/java/com/splanet/splanet/user/repository/UserRepository.java
  src/main/java/com/splanet/splanet/user/service/UserService.java
  src/main/resources/application.yml
  src/test/java/com/splanet/splanet/comment/entity/CommentTest.java
  src/test/java/com/splanet/splanet/comment/service/CommentServiceTest.java
  src/test/java/com/splanet/splanet/payment/service/PaymentServiceTest.java
  src/test/java/com/splanet/splanet/plan/entity/PlanTest.java
  src/test/java/com/splanet/splanet/plan/service/PlanServiceTest.java
  src/test/java/com/splanet/splanet/subscription/service/SubscriptionServiceTest.java
  src/test/java/com/splanet/splanet/user/service/UserServiceTest.java
Labels: 🔄merge

#45 [merge]: 5주차 코드 master에 병합
  build.gradle
  docker-compose.yml
  src/main/java/com/splanet/splanet/comment/controller/CommentController.java
  src/main/java/com/splanet/splanet/comment/dto/CommentRequest.java
  src/main/java/com/splanet/splanet/comment/dto/CommentResponse.java
  src/main/java/com/splanet/splanet/comment/entity/Comment.java
  src/main/java/com/splanet/splanet/comment/repository/CommentRepository.java
  src/main/java/com/splanet/splanet/comment/service/CommentService.java
  src/main/java/com/splanet/splanet/config/RedisConfig.java
  src/main/java/com/splanet/splanet/config/SecurityConfig.java
  src/main/java/com/splanet/splanet/core/exception/ErrorCode.java
  src/main/java/com/splanet/splanet/core/exception/GlobalExceptionHandler.java
  src/main/java/com/splanet/splanet/jwt/JwtAuthenticationFilter.java
  src/main/java/com/splanet/splanet/jwt/JwtTokenProvider.java
  src/main/java/com/splanet/splanet/jwt/controller/TokenController.java
  src/main/java/com/splanet/splanet/jwt/entity/RefreshToken.java
  src/main/java/com/splanet/splanet/jwt/repository/RefreshTokenRepository.java
  src/main/java/com/splanet/splanet/jwt/service/TokenService.java
  src/main/java/com/splanet/splanet/oauth/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/splanet/splanet/payment/controller/PaymentController.java
  src/main/java/com/splanet/splanet/payment/dto/PaymentRequest.java
  src/main/java/com/splanet/splanet/payment/dto/PaymentResponse.java
  src/main/java/com/splanet/splanet/payment/entity/Payment.java
  src/main/java/com/splanet/splanet/payment/service/PaymentService.java
  src/main/java/com/splanet/splanet/plan/controller/PlanController.java
  src/main/java/com/splanet/splanet/plan/dto/PlanRequestDto.java
  src/main/java/com/splanet/splanet/plan/dto/PlanResponseDto.java
  src/main/java/com/splanet/splanet/plan/entity/Plan.java
  src/main/java/com/splanet/splanet/plan/mapper/PlanMapper.java
  src/main/java/com/splanet/splanet/plan/repository/PlanRepository.java
  src/main/java/com/splanet/splanet/plan/service/PlanService.java
  src/main/java/com/splanet/splanet/subscription/controller/SubscriptionController.java
  src/main/java/com/splanet/splanet/subscription/dao/SubscriptionDao.java
  src/main/java/com/splanet/splanet/subscription/dto/SubscriptionDto.java
  src/main/java/com/splanet/splanet/subscription/dto/SubscriptionRequest.java
  src/main/java/com/splanet/splanet/subscription/dto/SubscriptionResponse.java
  src/main/java/com/splanet/splanet/subscription/entity/Subscription.java
  src/main/java/com/splanet/splanet/subscription/service/SubscriptionService.java
  src/main/java/com/splanet/splanet/user/controller/UserController.java
  src/main/java/com/splanet/splanet/user/entity/User.java
  src/main/java/com/splanet/splanet/user/repository/UserRepository.java
  src/main/java/com/splanet/splanet/user/service/UserService.java
  src/main/resources/application.yml
  src/test/java/com/splanet/splanet/comment/entity/CommentTest.java
  src/test/java/com/splanet/splanet/comment/service/CommentServiceTest.java
  src/test/java/com/splanet/splanet/payment/service/PaymentServiceTest.java
  src/test/java/com/splanet/splanet/plan/entity/PlanTest.java
  src/test/java/com/splanet/splanet/plan/service/PlanServiceTest.java
  src/test/java/com/splanet/splanet/subscription/service/SubscriptionServiceTest.java
  src/test/java/com/splanet/splanet/user/service/UserServiceTest.java
Labels: 🔄merge

#49 [refactor]: 5주차 피드백 반영
  src/main/java/com/splanet/splanet/comment/controller/CommentApi.java
  src/main/java/com/splanet/splanet/comment/controller/CommentController.java
  src/main/java/com/splanet/splanet/core/exception/GlobalExceptionHandler.java
  src/main/java/com/splanet/splanet/core/exception/ResponseConstants.java
  src/main/java/com/splanet/splanet/jwt/JwtTokenProvider.java
  src/main/java/com/splanet/splanet/jwt/controller/TokenApi.java
  src/main/java/com/splanet/splanet/jwt/controller/TokenController.java
  src/main/java/com/splanet/splanet/jwt/entity/RefreshToken.java
  src/main/java/com/splanet/splanet/jwt/service/TokenService.java
  src/main/java/com/splanet/splanet/oauth/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/splanet/splanet/payment/controller/PaymentApi.java
  src/main/java/com/splanet/splanet/payment/controller/PaymentController.java
  src/main/java/com/splanet/splanet/plan/controller/PlanApi.java
  src/main/java/com/splanet/splanet/plan/controller/PlanController.java
  src/main/java/com/splanet/splanet/subscription/controller/SubscriptionApi.java
  src/main/java/com/splanet/splanet/subscription/controller/SubscriptionController.java
  src/main/java/com/splanet/splanet/user/controller/UserApi.java
  src/main/java/com/splanet/splanet/user/controller/UserController.java
  src/main/resources/application.yml
Labels: ✨feature

#53 [bug]: @Value를 주입받지 못하는 문제 수정
  src/main/java/com/splanet/splanet/config/SecurityConfig.java
  src/main/java/com/splanet/splanet/core/properties/OAuth2Properties.java
  src/main/java/com/splanet/splanet/oauth/OAuth2AuthenticationSuccessHandler.java
Labels: 🐛bug

#50 [refactor]: 5주차 코드리뷰 반영하여 수정
  src/main/java/com/splanet/splanet/comment/controller/CommentApi.java
  src/main/java/com/splanet/splanet/comment/dto/CommentRequest.java
  src/main/java/com/splanet/splanet/comment/dto/CommentResponse.java
  src/main/java/com/splanet/splanet/comment/service/CommentService.java
  src/main/java/com/splanet/splanet/core/exception/ErrorCode.java
  src/main/java/com/splanet/splanet/payment/service/PaymentService.java
  src/main/java/com/splanet/splanet/subscription/service/SubscriptionService.java
  src/test/java/com/splanet/splanet/comment/service/CommentServiceTest.java
Labels: ✨feature

#58 [feature]: 팀 플랜 CRUD 구현
  src/main/java/com/splanet/splanet/plan/entity/TeamPlan.java
  src/main/java/com/splanet/splanet/team/controller/TeamApi.java
  src/main/java/com/splanet/splanet/team/controller/TeamController.java
  src/main/java/com/splanet/splanet/team/dto/TeamDto.java
  src/main/java/com/splanet/splanet/team/entity/Team.java
  src/main/java/com/splanet/splanet/team/repository/TeamUserRelationRepository.java
  src/main/java/com/splanet/splanet/team/service/TeamService.java
  src/main/java/com/splanet/splanet/teamplan/controller/TeamPlanApi.java
  src/main/java/com/splanet/splanet/teamplan/controller/TeamPlanController.java
  src/main/java/com/splanet/splanet/teamplan/dto/TeamPlanRequestDto.java
  src/main/java/com/splanet/splanet/teamplan/dto/TeamPlanResponseDto.java
  src/main/java/com/splanet/splanet/teamplan/entity/TeamPlan.java
  src/main/java/com/splanet/splanet/teamplan/mapper/TeamPlanMapper.java
  src/main/java/com/splanet/splanet/teamplan/repository/TeamPlanRepository.java
  src/main/java/com/splanet/splanet/teamplan/service/TeamPlanService.java
  src/test/java/com/splanet/splanet/team/service/TeamServiceTest.java
Labels: ✨feature

#57 [refactor]: User 정보 조회시 구독여부 업데이트 설정하기
  src/main/java/com/splanet/splanet/subscription/controller/SubscriptionController.java
  src/main/java/com/splanet/splanet/subscription/service/SubscriptionService.java
  src/main/java/com/splanet/splanet/user/entity/User.java
  src/test/java/com/splanet/splanet/subscription/service/SubscriptionServiceTest.java
Labels: ✨feature

#59 [feature]: PreviewPlan 구현
  src/main/java/com/splanet/splanet/core/exception/ErrorCode.java
  src/main/java/com/splanet/splanet/plan/controller/PlanApi.java
  src/main/java/com/splanet/splanet/plan/controller/PlanController.java
  src/main/java/com/splanet/splanet/plan/dto/PlanRequestDto.java
  src/main/java/com/splanet/splanet/plan/entity/Plan.java
  src/main/java/com/splanet/splanet/plan/service/PlanService.java
  src/main/java/com/splanet/splanet/previewplan/controller/PreviewPlanApi.java
  src/main/java/com/splanet/splanet/previewplan/controller/PreviewPlanController.java
  src/main/java/com/splanet/splanet/previewplan/dto/PlanCardRequestDto.java
  src/main/java/com/splanet/splanet/previewplan/dto/PlanCardResponseDto.java
  src/main/java/com/splanet/splanet/previewplan/dto/PlanGroupWithCardsResponseDto.java
  src/main/java/com/splanet/splanet/previewplan/entity/PlanCard.java
  src/main/java/com/splanet/splanet/previewplan/entity/PlanGroup.java
  src/main/java/com/splanet/splanet/previewplan/entity/PreviewPlan.java
  src/main/java/com/splanet/splanet/previewplan/repository/PlanCardRepository.java
  src/main/java/com/splanet/splanet/previewplan/repository/PlanGroupRepository.java
  src/main/java/com/splanet/splanet/previewplan/repository/PreviewPlanRepository.java
  src/main/java/com/splanet/splanet/previewplan/service/PreviewPlanService.java
  src/test/java/com/splanet/splanet/previewplan/service/PreviewPlanServiceTest.java
Labels: ✨feature

#65 [feature]: CI 워크플로우 작성
  .github/workflows/ci.yml
  src/main/java/com/splanet/splanet/jwt/JwtTokenProvider.java
Labels: ✨feature

#67 [feat]: previewPlan TTL을 제대로 적용하지 않은 문제 수정
  src/main/java/com/splanet/splanet/previewplan/entity/PlanCard.java
  src/main/java/com/splanet/splanet/previewplan/entity/PlanGroup.java
  src/main/java/com/splanet/splanet/previewplan/entity/PreviewPlan.java
  src/main/java/com/splanet/splanet/previewplan/service/PreviewPlanService.java
Labels: ✨feature

#73 feat: cd pipeline
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  Dockerfile
  build.gradle
  docker-compose.yml
  src/main/java/com/splanet/splanet/core/properties/JwtProperties.java
  src/main/java/com/splanet/splanet/jwt/JwtTokenProvider.java
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
  src/test/java/com/splanet/splanet/SplanetApplicationTests.java
  src/test/resources/application.yml
Labels: ✨feature

#76 [refactor]: CI/CD 수정
  .github/workflows/cd.yml
  .github/workflows/ci.yml
Labels: ♻️refactor

#69 [feature]: STT 구현
  build.gradle
  src/main/java/com/splanet/splanet/config/WebConfig.java
  src/main/java/com/splanet/splanet/config/WebSocketConfig.java
  src/main/java/com/splanet/splanet/core/handler/SpeechWebSocketHandler.java
  src/main/java/com/splanet/splanet/core/properties/ClovaProperties.java
  src/main/java/com/splanet/splanet/jwt/JwtAuthenticationFilter.java
  src/main/java/com/splanet/splanet/stt/service/ClovaSpeechGrpcService.java
  src/main/java/com/splanet/splanet/stt/service/ClovaSpeechService.java
  src/main/proto/nest.proto
Labels: ✨feature

#63 [feature]: friend API 구현
  src/main/java/com/splanet/splanet/core/exception/ErrorCode.java
  src/main/java/com/splanet/splanet/friend/controller/FriendApi.java
  src/main/java/com/splanet/splanet/friend/controller/FriendController.java
  src/main/java/com/splanet/splanet/friend/dto/FriendResponse.java
  src/main/java/com/splanet/splanet/friend/entity/Friend.java
  src/main/java/com/splanet/splanet/friend/repository/FriendRepository.java
  src/main/java/com/splanet/splanet/friend/service/FriendService.java
  src/main/java/com/splanet/splanet/friendRequest/controller/FriendRequestApi.java
  src/main/java/com/splanet/splanet/friendRequest/controller/FriendRequestController.java
  src/main/java/com/splanet/splanet/friendRequest/dto/FriendRequestCreateRequest.java
  src/main/java/com/splanet/splanet/friendRequest/dto/ReceivedFriendRequestResponse.java
  src/main/java/com/splanet/splanet/friendRequest/dto/SentFriendRequestResponse.java
  src/main/java/com/splanet/splanet/friendRequest/dto/SuccessResponse.java
  src/main/java/com/splanet/splanet/friendRequest/entity/FriendRequest.java
  src/main/java/com/splanet/splanet/friendRequest/repository/FriendRequestRepository.java
  src/main/java/com/splanet/splanet/friendRequest/service/FriendRequestService.java
  src/main/java/com/splanet/splanet/plan/repository/PlanRepository.java
  src/test/java/com/splanet/splanet/friend/service/FriendServiceTest.java
  src/test/java/com/splanet/splanet/friendRequest/service/FriendRequestServiceTest.java
Labels: ✨feature

#74 [refactor]: SpringAi GPT 연결 및 프롬프트 작성
  build.gradle
  src/main/java/com/splanet/splanet/gpt/Message.java
  src/main/java/com/splanet/splanet/gpt/OpenAiChatClient.java
  src/main/java/com/splanet/splanet/gpt/OpenAiProperties.java
  src/main/java/com/splanet/splanet/gpt/Prompt.java
  src/main/java/com/splanet/splanet/gpt/RequestBody.java
  src/main/java/com/splanet/splanet/gpt/SchedulePromptGenerator.java
  src/main/java/com/splanet/splanet/gpt/ScheduleRequest.java
  src/main/java/com/splanet/splanet/gpt/ScheduleResponse.java
Labels: ✨feature

#77 [merge]: 7~8주차 진행사항 develop에 머지
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  Dockerfile
  build.gradle
  docker-compose.yml
  src/main/java/com/splanet/splanet/config/WebConfig.java
  src/main/java/com/splanet/splanet/config/WebSocketConfig.java
  src/main/java/com/splanet/splanet/core/exception/ErrorCode.java
  src/main/java/com/splanet/splanet/core/handler/SpeechWebSocketHandler.java
  src/main/java/com/splanet/splanet/core/properties/ClovaProperties.java
  src/main/java/com/splanet/splanet/core/properties/JwtProperties.java
  src/main/java/com/splanet/splanet/friend/controller/FriendApi.java
  src/main/java/com/splanet/splanet/friend/controller/FriendController.java
  src/main/java/com/splanet/splanet/friend/dto/FriendResponse.java
  src/main/java/com/splanet/splanet/friend/entity/Friend.java
  src/main/java/com/splanet/splanet/friend/repository/FriendRepository.java
  src/main/java/com/splanet/splanet/friend/service/FriendService.java
  src/main/java/com/splanet/splanet/friendRequest/controller/FriendRequestApi.java
  src/main/java/com/splanet/splanet/friendRequest/controller/FriendRequestController.java
  src/main/java/com/splanet/splanet/friendRequest/dto/FriendRequestCreateRequest.java
  src/main/java/com/splanet/splanet/friendRequest/dto/ReceivedFriendRequestResponse.java
  src/main/java/com/splanet/splanet/friendRequest/dto/SentFriendRequestResponse.java
  src/main/java/com/splanet/splanet/friendRequest/dto/SuccessResponse.java
  src/main/java/com/splanet/splanet/friendRequest/entity/FriendRequest.java
  src/main/java/com/splanet/splanet/friendRequest/repository/FriendRequestRepository.java
  src/main/java/com/splanet/splanet/friendRequest/service/FriendRequestService.java
  src/main/java/com/splanet/splanet/gpt/Message.java
  src/main/java/com/splanet/splanet/gpt/OpenAiChatClient.java
  src/main/java/com/splanet/splanet/gpt/OpenAiProperties.java
  src/main/java/com/splanet/splanet/gpt/Prompt.java
  src/main/java/com/splanet/splanet/gpt/RequestBody.java
  src/main/java/com/splanet/splanet/gpt/SchedulePromptGenerator.java
  src/main/java/com/splanet/splanet/gpt/ScheduleRequest.java
  src/main/java/com/splanet/splanet/gpt/ScheduleResponse.java
  src/main/java/com/splanet/splanet/jwt/JwtAuthenticationFilter.java
  src/main/java/com/splanet/splanet/jwt/JwtTokenProvider.java
  src/main/java/com/splanet/splanet/plan/repository/PlanRepository.java
  src/main/java/com/splanet/splanet/previewplan/entity/PlanCard.java
  src/main/java/com/splanet/splanet/previewplan/entity/PlanGroup.java
  src/main/java/com/splanet/splanet/previewplan/entity/PreviewPlan.java
  src/main/java/com/splanet/splanet/previewplan/service/PreviewPlanService.java
  src/main/java/com/splanet/splanet/stt/service/ClovaSpeechGrpcService.java
  src/main/java/com/splanet/splanet/stt/service/ClovaSpeechService.java
  src/main/proto/nest.proto
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
  src/test/java/com/splanet/splanet/SplanetApplicationTests.java
  src/test/java/com/splanet/splanet/friend/service/FriendServiceTest.java
  src/test/java/com/splanet/splanet/friendRequest/service/FriendRequestServiceTest.java
  src/test/resources/application.yml
Labels: 🔄merge

#78 [merge]: 7~8주차 진행사항 master에 머지
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  Dockerfile
  build.gradle
  docker-compose.yml
  src/main/java/com/splanet/splanet/config/WebConfig.java
  src/main/java/com/splanet/splanet/config/WebSocketConfig.java
  src/main/java/com/splanet/splanet/core/exception/ErrorCode.java
  src/main/java/com/splanet/splanet/core/handler/SpeechWebSocketHandler.java
  src/main/java/com/splanet/splanet/core/properties/ClovaProperties.java
  src/main/java/com/splanet/splanet/core/properties/JwtProperties.java
  src/main/java/com/splanet/splanet/friend/controller/FriendApi.java
  src/main/java/com/splanet/splanet/friend/controller/FriendController.java
  src/main/java/com/splanet/splanet/friend/dto/FriendResponse.java
  src/main/java/com/splanet/splanet/friend/entity/Friend.java
  src/main/java/com/splanet/splanet/friend/repository/FriendRepository.java
  src/main/java/com/splanet/splanet/friend/service/FriendService.java
  src/main/java/com/splanet/splanet/friendRequest/controller/FriendRequestApi.java
  src/main/java/com/splanet/splanet/friendRequest/controller/FriendRequestController.java
  src/main/java/com/splanet/splanet/friendRequest/dto/FriendRequestCreateRequest.java
  src/main/java/com/splanet/splanet/friendRequest/dto/ReceivedFriendRequestResponse.java
  src/main/java/com/splanet/splanet/friendRequest/dto/SentFriendRequestResponse.java
  src/main/java/com/splanet/splanet/friendRequest/dto/SuccessResponse.java
  src/main/java/com/splanet/splanet/friendRequest/entity/FriendRequest.java
  src/main/java/com/splanet/splanet/friendRequest/repository/FriendRequestRepository.java
  src/main/java/com/splanet/splanet/friendRequest/service/FriendRequestService.java
  src/main/java/com/splanet/splanet/gpt/Message.java
  src/main/java/com/splanet/splanet/gpt/OpenAiChatClient.java
  src/main/java/com/splanet/splanet/gpt/OpenAiProperties.java
  src/main/java/com/splanet/splanet/gpt/Prompt.java
  src/main/java/com/splanet/splanet/gpt/RequestBody.java
  src/main/java/com/splanet/splanet/gpt/SchedulePromptGenerator.java
  src/main/java/com/splanet/splanet/gpt/ScheduleRequest.java
  src/main/java/com/splanet/splanet/gpt/ScheduleResponse.java
  src/main/java/com/splanet/splanet/jwt/JwtAuthenticationFilter.java
  src/main/java/com/splanet/splanet/jwt/JwtTokenProvider.java
  src/main/java/com/splanet/splanet/plan/repository/PlanRepository.java
  src/main/java/com/splanet/splanet/previewplan/entity/PlanCard.java
  src/main/java/com/splanet/splanet/previewplan/entity/PlanGroup.java
  src/main/java/com/splanet/splanet/previewplan/entity/PreviewPlan.java
  src/main/java/com/splanet/splanet/previewplan/service/PreviewPlanService.java
  src/main/java/com/splanet/splanet/stt/service/ClovaSpeechGrpcService.java
  src/main/java/com/splanet/splanet/stt/service/ClovaSpeechService.java
  src/main/proto/nest.proto
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
  src/test/java/com/splanet/splanet/SplanetApplicationTests.java
  src/test/java/com/splanet/splanet/friend/service/FriendServiceTest.java
  src/test/java/com/splanet/splanet/friendRequest/service/FriendRequestServiceTest.java
  src/test/resources/application.yml
Labels: 🔄merge

#79 [review]: 7~8주차 코드리뷰
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  Dockerfile
  build.gradle
  docker-compose.yml
  src/main/java/com/splanet/splanet/config/WebConfig.java
  src/main/java/com/splanet/splanet/config/WebSocketConfig.java
  src/main/java/com/splanet/splanet/core/exception/ErrorCode.java
  src/main/java/com/splanet/splanet/core/handler/SpeechWebSocketHandler.java
  src/main/java/com/splanet/splanet/core/properties/ClovaProperties.java
  src/main/java/com/splanet/splanet/core/properties/JwtProperties.java
  src/main/java/com/splanet/splanet/friend/controller/FriendApi.java
  src/main/java/com/splanet/splanet/friend/controller/FriendController.java
  src/main/java/com/splanet/splanet/friend/dto/FriendResponse.java
  src/main/java/com/splanet/splanet/friend/entity/Friend.java
  src/main/java/com/splanet/splanet/friend/repository/FriendRepository.java
  src/main/java/com/splanet/splanet/friend/service/FriendService.java
  src/main/java/com/splanet/splanet/friendRequest/controller/FriendRequestApi.java
  src/main/java/com/splanet/splanet/friendRequest/controller/FriendRequestController.java
  src/main/java/com/splanet/splanet/friendRequest/dto/FriendRequestCreateRequest.java
  src/main/java/com/splanet/splanet/friendRequest/dto/ReceivedFriendRequestResponse.java
  src/main/java/com/splanet/splanet/friendRequest/dto/SentFriendRequestResponse.java
  src/main/java/com/splanet/splanet/friendRequest/dto/SuccessResponse.java
  src/main/java/com/splanet/splanet/friendRequest/entity/FriendRequest.java
  src/main/java/com/splanet/splanet/friendRequest/repository/FriendRequestRepository.java
  src/main/java/com/splanet/splanet/friendRequest/service/FriendRequestService.java
  src/main/java/com/splanet/splanet/gpt/Message.java
  src/main/java/com/splanet/splanet/gpt/OpenAiChatClient.java
  src/main/java/com/splanet/splanet/gpt/OpenAiProperties.java
  src/main/java/com/splanet/splanet/gpt/Prompt.java
  src/main/java/com/splanet/splanet/gpt/RequestBody.java
  src/main/java/com/splanet/splanet/gpt/SchedulePromptGenerator.java
  src/main/java/com/splanet/splanet/gpt/ScheduleRequest.java
  src/main/java/com/splanet/splanet/gpt/ScheduleResponse.java
  src/main/java/com/splanet/splanet/jwt/JwtAuthenticationFilter.java
  src/main/java/com/splanet/splanet/jwt/JwtTokenProvider.java
  src/main/java/com/splanet/splanet/plan/repository/PlanRepository.java
  src/main/java/com/splanet/splanet/previewplan/entity/PlanCard.java
  src/main/java/com/splanet/splanet/previewplan/entity/PlanGroup.java
  src/main/java/com/splanet/splanet/previewplan/entity/PreviewPlan.java
  src/main/java/com/splanet/splanet/previewplan/service/PreviewPlanService.java
  src/main/java/com/splanet/splanet/stt/service/ClovaSpeechGrpcService.java
  src/main/java/com/splanet/splanet/stt/service/ClovaSpeechService.java
  src/main/proto/nest.proto
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
  src/test/java/com/splanet/splanet/SplanetApplicationTests.java
  src/test/java/com/splanet/splanet/friend/service/FriendServiceTest.java
  src/test/java/com/splanet/splanet/friendRequest/service/FriendRequestServiceTest.java
  src/test/resources/application.yml
Labels: 💬review

#83 [refactor]: 배포 후 문제되는 부분 수정
  .github/workflows/cd.yml
  src/main/java/com/splanet/splanet/config/SwaggerConfig.java
  src/main/resources/application-prod.yml
Labels: ♻️refactor

#86 [bug]: CORS 해결 및 잡다한 부분 수정
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  src/main/java/com/splanet/splanet/config/SecurityConfig.java
  src/main/java/com/splanet/splanet/config/WebConfig.java
  src/main/java/com/splanet/splanet/user/controller/UserApi.java
  src/main/java/com/splanet/splanet/user/controller/UserController.java
  src/main/java/com/splanet/splanet/user/service/UserService.java
  src/main/resources/application-prod.yml
Labels: 🐛bug

#84 [refactor] SpringAi로 gpt 연결
  build.gradle
  src/main/java/com/splanet/splanet/config/OpenAiConfig.java
  src/main/java/com/splanet/splanet/core/properties/GptProperties.java
  src/main/java/com/splanet/splanet/gpt/GptRequest.java
  src/main/java/com/splanet/splanet/gpt/Message.java
  src/main/java/com/splanet/splanet/gpt/OpenAiChatClient.java
  src/main/java/com/splanet/splanet/gpt/Prompt.java
  src/main/java/com/splanet/splanet/gpt/RequestBody.java
  src/main/java/com/splanet/splanet/gpt/SchedulePromptGenerator.java
  src/main/java/com/splanet/splanet/gpt/ScheduleRequest.java
  src/main/java/com/splanet/splanet/gpt/ScheduleResponse.java
  src/main/java/com/splanet/splanet/gpt/controller/GptApi.java
  src/main/java/com/splanet/splanet/gpt/controller/GptController.java
  src/main/java/com/splanet/splanet/gpt/controller/GptPlanSaveController.java
  src/main/java/com/splanet/splanet/gpt/service/DeviceIdGenerator.java
  src/main/java/com/splanet/splanet/gpt/service/GptPlanSaveService.java
  src/main/java/com/splanet/splanet/gpt/service/GptService.java
  src/main/java/com/splanet/splanet/jwt/JwtAuthenticationFilter.java
  src/main/java/com/splanet/splanet/plan/dto/PlanResponseDto.java
  src/main/java/com/splanet/splanet/plan/repository/PlanRepository.java
  src/main/java/com/splanet/splanet/plan/service/PlanService.java
  src/main/java/com/splanet/splanet/previewplan/dto/PlanGroupRequestDto.java
  src/main/resources/application.yml
Labels: ✨feature
