Repository kakao-tech-campus-2nd-step3/Team3_BE, pull requests merged in 2024-11, with the labels that each got.

#89 [refactor]: 친구요청 삭제 메소드 구현
  src/main/java/com/splanet/splanet/friendRequest/controller/FriendRequestApi.java
  src/main/java/com/splanet/splanet/friendRequest/controller/FriendRequestController.java
  src/main/java/com/splanet/splanet/friendRequest/service/FriendRequestService.java
  src/test/java/com/splanet/splanet/friendRequest/service/FriendRequestServiceTest.java
Labels: ✨feature, ♻️refactor

#91 [test]: 테스트 이슈 해결 및 User 통합테스트, 인수테스트 작성
  .github/workflows/ci.yml
  build.gradle
  src/main/java/com/splanet/splanet/comment/service/CommentService.java
  src/test/java/com/splanet/splanet/SplanetApplicationTests.java
  src/test/java/com/splanet/splanet/user/controller/UserControllerAcceptanceTest.java
  src/test/java/com/splanet/splanet/user/controller/UserControllerIntegrationTest.java
  src/test/resources/application-test.yml
  src/test/resources/application.yml
Labels: ✨feature

#97 [feat]: Blue/Green 무중단 배포
  .github/workflows/cd.yml
Labels: ✨feature

#101 [feat]: GPT 로직 보완
  README.md
  src/main/java/com/splanet/splanet/core/exception/ErrorCode.java
  src/main/java/com/splanet/splanet/core/exception/GlobalExceptionHandler.java
  src/main/java/com/splanet/splanet/core/exception/InvalidPlanFormatException.java
  src/main/java/com/splanet/splanet/gpt/controller/GptApi.java
  src/main/java/com/splanet/splanet/gpt/controller/GptController.java
  src/main/java/com/splanet/splanet/gpt/controller/GptPlanSaveController.java
  src/main/java/com/splanet/splanet/gpt/service/GptPlanSaveService.java
  src/main/java/com/splanet/splanet/gpt/service/GptService.java
  src/main/java/com/splanet/splanet/jwt/JwtAuthenticationFilter.java
  src/main/java/com/splanet/splanet/previewplan/controller/PreviewPlanApi.java
  src/main/java/com/splanet/splanet/previewplan/controller/PreviewPlanController.java
  src/main/java/com/splanet/splanet/previewplan/service/PreviewPlanService.java
Labels: ✨feature

#110 [bug]: timestamp 형식도 Redis 에 바로 저장되도록 수정
  src/main/java/com/splanet/splanet/gpt/service/GptPlanSaveService.java
Labels: 🐛bug

#116 [fix]: 시간 표현 형식때문에 수정, 조회가 제대로 안되는 오류
  src/main/java/com/splanet/splanet/core/exception/ErrorCode.java
  src/main/java/com/splanet/splanet/previewplan/dto/PlanCardResponseDto.java
  src/test/java/com/splanet/splanet/previewplan/service/PreviewPlanServiceTest.java
Labels: 🐛bug

#119 [refactor]: 타임스탬프 로직 롤백
  src/main/java/com/splanet/splanet/friend/service/FriendService.java
  src/main/java/com/splanet/splanet/gpt/service/GptPlanSaveService.java
  src/main/java/com/splanet/splanet/plan/controller/PlanApi.java
  src/main/java/com/splanet/splanet/plan/controller/PlanController.java
  src/main/java/com/splanet/splanet/plan/dto/PlanRequestDto.java
  src/main/java/com/splanet/splanet/plan/dto/PlanResponseDto.java
  src/main/java/com/splanet/splanet/plan/entity/Plan.java
  src/main/java/com/splanet/splanet/plan/mapper/PlanMapper.java
  src/main/java/com/splanet/splanet/plan/repository/PlanRepository.java
  src/main/java/com/splanet/splanet/plan/service/PlanService.java
  src/main/java/com/splanet/splanet/previewplan/controller/PreviewPlanApi.java
  src/main/java/com/splanet/splanet/previewplan/controller/PreviewPlanController.java
  src/main/java/com/splanet/splanet/previewplan/dto/PlanCardResponseDto.java
  src/main/java/com/splanet/splanet/previewplan/dto/PlanGroupRequestDto.java
  src/main/java/com/splanet/splanet/previewplan/dto/PlanGroupWithCardsResponseDto.java
  src/main/java/com/splanet/splanet/previewplan/entity/PlanCard.java
  src/main/java/com/splanet/splanet/previewplan/entity/PlanGroup.java
  src/main/java/com/splanet/splanet/previewplan/entity/PreviewPlan.java
  src/main/java/com/splanet/splanet/previewplan/service/PreviewPlanService.java
  src/test/java/com/splanet/splanet/plan/service/PlanServiceTest.java
  src/test/java/com/splanet/splanet/previewplan/service/PreviewPlanServiceTest.java
Labels: ♻️refactor

#124 [bug]: CORS 해결
  src/main/java/com/splanet/splanet/config/SecurityConfig.java
Labels: 🐛bug

#126 [bug]: health check가 안되던 문제 해결
  src/main/resources/application.yml
Labels: 🐛bug

#130 [test]: Plan 통합, 인수 테스트 추가
  src/main/java/com/splanet/splanet/core/exception/GlobalExceptionHandler.java
  src/main/java/com/splanet/splanet/plan/service/PlanService.java
  src/main/java/com/splanet/splanet/teamplan/service/TeamPlanService.java
  src/test/java/com/splanet/splanet/plan/controller/PlanControllerAcceptanceTest.java
  src/test/java/com/splanet/splanet/plan/controller/PlanControllerIntegrationTest.java
  src/test/java/com/splanet/splanet/plan/service/PlanServiceTest.java
Labels: ♻️refactor

#133 refactor: 로그 기록 로직 수정
  splanet-test.log
  splanet.log
  src/main/java/com/splanet/splanet/config/SecurityConfig.java
  src/main/java/com/splanet/splanet/log/aspect/LoginSuccessAspect.java
  src/main/java/com/splanet/splanet/oauth/CustomOAuth2UserService.java
  src/test/java/com/splanet/splanet/log/aspect/LoginSuccessAspectTest.java
Labels: ♻️refactor

#132 [refactor]: CD 파이프라인 보완 (에러 처리 및 롤백 로직)
  .github/workflows/cd.yml
  .github/workflows/rollback.yml
Labels: ♻️refactor

#108 [refactor]: 단위테스트 작성 (통합테스트도 작성하고 푸시하겠습니다.)
  src/main/java/com/splanet/splanet/comment/controller/CommentApi.java
  src/main/java/com/splanet/splanet/comment/controller/CommentController.java
  src/main/java/com/splanet/splanet/comment/dto/CommentRequest.java
  src/main/java/com/splanet/splanet/comment/service/CommentService.java
  src/main/java/com/splanet/splanet/core/exception/ErrorCode.java
  src/main/java/com/splanet/splanet/friend/controller/FriendController.java
  src/main/java/com/splanet/splanet/gpt/controller/GptPlanSaveApi.java
  src/main/java/com/splanet/splanet/gpt/controller/GptPlanSaveController.java
  src/main/java/com/splanet/splanet/notification/controller/NotificationApi.java
  src/main/java/com/splanet/splanet/notification/controller/NotificationController.java
  src/main/java/com/splanet/splanet/payment/controller/PaymentApi.java
  src/main/java/com/splanet/splanet/payment/controller/PaymentController.java
  src/main/java/com/splanet/splanet/payment/dto/PaymentRequest.java
  src/main/java/com/splanet/splanet/payment/dto/PaymentResponse.java
  src/main/java/com/splanet/splanet/payment/service/PaymentService.java
  src/main/java/com/splanet/splanet/subscription/entity/Subscription.java
  src/test/java/com/splanet/splanet/comment/controller/CommentControllerIntegrationTest.java
  src/test/java/com/splanet/splanet/comment/service/CommentServiceTest.java
  src/test/java/com/splanet/splanet/notification/service/FcmTokenServiceTest.java
  src/test/java/com/splanet/splanet/notification/service/NotificationServiceTest.java
  src/test/java/com/splanet/splanet/payment/service/PaymentServiceTest.java
  src/test/java/com/splanet/splanet/teamplan/service/TeamPlanServiceTest.java
Labels: ♻️refactor

#141 [refactor]: 웹소켓 허용 경로 제한
  src/main/java/com/splanet/splanet/config/WebSocketConfig.java
Labels: ♻️refactor

#147 [refactor]: 11주차 피드백 반영
  src/main/java/com/splanet/splanet/core/properties/OAuth2Properties.java
  src/main/java/com/splanet/splanet/gpt/controller/GptController.java
  src/main/java/com/splanet/splanet/gpt/service/GptService.java
  src/main/java/com/splanet/splanet/oauth/OAuth2AuthenticationSuccessHandler.java
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
Labels: ♻️refactor

#149 [refactor]: 요청 환경에 따라서 리다이렉트를 다르게 처리하도록 수정
  src/main/java/com/splanet/splanet/oauth/OAuth2AuthenticationSuccessHandler.java
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
Labels: ♻️refactor

#150 [refactor]: 로그인 환경에 따라 다르게 처리 수정
  src/main/java/com/splanet/splanet/oauth/OAuth2AuthenticationSuccessHandler.java
Labels: ♻️refactor

#153 [refactor]: 에러메시지 NULL 처리
  src/main/java/com/splanet/splanet/core/exception/GlobalExceptionHandler.java
Labels: ♻️refactor

#156 bug: log 버그 해결
  splanet-test.log
  splanet.log
  src/main/java/com/splanet/splanet/log/interceptor/ApiLoggingInterceptor.java
  src/main/java/com/splanet/splanet/log/service/LogService.java
  src/main/java/com/splanet/splanet/oauth/OAuth2AuthenticationSuccessHandler.java
Labels: 🐛bug

#157 [bug]: 내 친구 목록에서 친구 삭제시 친구의 친구 목록에는 남아있는 버그
  splanet-test.log
  src/main/java/com/splanet/splanet/comment/controller/CommentApi.java
  src/main/java/com/splanet/splanet/comment/controller/CommentController.java
  src/main/java/com/splanet/splanet/comment/dto/CommentRequest.java
  src/main/java/com/splanet/splanet/comment/service/CommentService.java
  src/main/java/com/splanet/splanet/core/exception/ErrorCode.java
  src/main/java/com/splanet/splanet/friend/service/FriendService.java
  src/main/java/com/splanet/splanet/subscription/controller/SubscriptionApi.java
  src/main/java/com/splanet/splanet/team/controller/TeamApi.java
  src/main/java/com/splanet/splanet/team/controller/TeamController.java
  src/main/java/com/splanet/splanet/team/repository/TeamRepository.java
  src/main/java/com/splanet/splanet/team/service/TeamService.java
  src/main/java/com/splanet/splanet/teamplan/controller/TeamPlanController.java
  src/test/java/com/splanet/splanet/comment/controller/CommentControllerIntegrationTest.java
  src/test/java/com/splanet/splanet/comment/service/CommentServiceTest.java
  src/test/java/com/splanet/splanet/friend/controller/FriendControllerIntegrationTest.java
  src/test/java/com/splanet/splanet/friendRequest/controller/FriendRequestControllerIntegrationTest.java
  src/test/java/com/splanet/splanet/payment/controller/PaymentControllerIntegrationTest.java
  src/test/java/com/splanet/splanet/previewplan/controller/PreviewPlanControllerIntegrationTest.java
  src/test/java/com/splanet/splanet/subscription/controller/SubscriptionControllerIntegrationTest.java
  src/test/java/com/splanet/splanet/team/controller/TeamControllerIntegrationTest.java
  src/test/java/com/splanet/splanet/team/service/TeamServiceTest.java
  src/test/java/com/splanet/splanet/teamplan/controller/TeamPlanControllerIntegrationTest.java
Labels: 🐛bug

#169 [refactor]: FCM 토큰 로직 수정 및 GPT api 보완
  .github/workflows/cd.yml
  .gitignore
  src/main/java/com/splanet/splanet/core/exception/ErrorCode.java
  src/main/java/com/splanet/splanet/gpt/service/GptService.java
  src/main/java/com/splanet/splanet/notification/controller/FcmTokenApi.java
  src/main/java/com/splanet/splanet/notification/controller/FcmTokenController.java
  src/main/java/com/splanet/splanet/notification/repository/FcmTokenRepository.java
  src/main/java/com/splanet/splanet/notification/service/FcmTokenService.java
  src/main/java/com/splanet/splanet/notification/service/NotificationService.java
  src/main/java/com/splanet/splanet/plan/dto/PlanResponseDto.java
  src/main/java/com/splanet/splanet/plan/dto/PlanTimeDto.java
  src/main/java/com/splanet/splanet/plan/repository/PlanRepository.java
  src/main/java/com/splanet/splanet/plan/service/PlanService.java
  src/test/java/com/splanet/splanet/notification/service/FcmTokenServiceTest.java
Labels: ♻️refactor

#171 [feat]: 코드 커버리지 측정 자동화
  .github/workflows/ci.yml
  build.gradle
Labels: ✨feature

#173 bug: 로깅 로직관련 버그 해결
  src/main/java/com/splanet/splanet/core/exception/GlobalExceptionHandler.java
  src/main/java/com/splanet/splanet/log/interceptor/ApiLoggingInterceptor.java
  src/main/java/com/splanet/splanet/oauth/OAuth2AuthenticationSuccessHandler.java
Labels: 🐛bug
